### ISSUE TITLE
missing numpy module

### ISSUE THREAD

**Issue by gerald-b** [joshuaflanagan/stl2scad#3]
Hi,
i'm running Ubuntu 18.04.2 LTS Desktop 64 Bit.
on my machine python 2.7 and 3.6 is installed.

if i run on python2 i got an error:
```
Traceback (most recent call last):
  File "./stl2scad.py", line 38, in <module>
    import numpy
ImportError: No module named numpy
```

On python3 there is no issue.

Maybe you want to update the readme?

This information would be helpfull for me. I'm not an python developer....

**Comment by baradhili** [comment]
just for the record... assuming you have `python` as a v3
then `pip install numpy`
